version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "felipe@mota#"
      MYSQL_DATABASE: "BD_AUTENTICACAO"
      TZ: "America/Sao_Paulo"
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - mysql_data:/var/lib/mysql
      # use a path relative to THIS compose file
      - ./BancoDeDadosOld/BD_AUTENTICACAO.sql:/docker-entrypoint-initdb.d/BD_AUTENTICACAO.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pfelipe@mota#"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:
