services:

  postgres-for-api-mvc-master-data:
    container_name: api-mvc-master-data-db-container
    image: postgres:15
    environment:
      POSTGRES_DB: master_data
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d master_data" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres-for-api-mvc-master-data-volume:/var/lib/postgresql/data

volumes:
  postgres-for-api-mvc-master-data-volume:
