/**
 * Author:  felipe
 * Created: Oct 28, 2017
 */

CREATE DATABASE IF NOT EXISTS BD_AUTENTICACAO;
CREATE USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'felipe@mota#';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

USE BD_AUTENTICACAO;

CREATE TABLE AUTENTICACAO_USUARIO(
	ID_AUTENTICACAO_USUARIO INTEGER NOT NULL AUTO_INCREMENT,
	USUARIO VARCHAR(15) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	STATUS_DE_PREVILEGIO INTEGER NOT NULL,
        NOME_USUARIO VARCHAR(45) NOT NULL,
	CONSTRAINT PRIMARY KEY(ID_AUTENTICACAO_USUARIO)
)ENGINE = innodb;

DESC AUTENTICACAO_USUARIO;
SHOW TABLES;

INSERT INTO AUTENTICACAO_USUARIO(USUARIO,SENHA,STATUS_DE_PREVILEGIO,NOME_USUARIO)
	VALUES("administrador","123@2017",1,"FELIPE VIEIRA MOTA");

INSERT INTO AUTENTICACAO_USUARIO(USUARIO,SENHA,STATUS_DE_PREVILEGIO,NOME_USUARIO)
	VALUES("caio","789",1,"CAIO VINICIUS");




SELECT * FROM AUTENTICACAO_USUARIO;	