/**
 * Author:  felipe
 * Created: Oct 28, 2017
 */

DROP DATABASE BD_REGRA;
CREATE DATABASE BD_REGRA;
USE BD_REGRA;


CREATE TABLE IF NOT EXISTS ALUNO (
    CODIGO_CARTAO_RFID INTEGER(11) NOT NULL,  
    NOME_ALUNO VARCHAR(255) NOT NULL,
    NOME_MAE_ALUNO VARCHAR(255) NOT NULL,
    NOME_PAI_ALUNO VARCHAR(45) NOT NULL,
    CODIGO_MATRICULA_ALUNO INTEGER NOT NULL,  
    CPF_ALUNO VARCHAR(45) NOT NULL,
    SEXO_ALUNO VARCHAR(45) NOT NULL,
    IDADE_ALUNO VARCHAR(45) NOT NULL,
    DATA_NASCIMENTO_ALUNO VARCHAR(45) NOT NULL,
    EMAIL_ALUNO VARCHAR(45) NOT NULL,
    CELULAR_ALUNO VARCHAR(45) NOT NULL,
    RG_ALUNO VARCHAR(45) NULL,
  CONSTRAINT PRIMARY KEY (CODIGO_CARTAO_RFID))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ANO_SEMESTRE(
    ID_ANO_SEMESTRE INTEGER NOT NULL AUTO_INCREMENT, 
    ANO_SEMESTRE VARCHAR(45), 
    OBSERVACOES VARCHAR(255),
    CONSTRAINT PRIMARY KEY (ID_ANO_SEMESTRE)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS CURSO(
    ID_CURSO INTEGER NOT NULL AUTO_INCREMENT, 
    NOME_CURSO VARCHAR(45), 
    TIPO_CURSO VARCHAR(45), 
    DURACAO VARCHAR(45),
    QTD_SEMESTRES VARCHAR(100),
    CARGA_HORARIA VARCHAR(45),
    OBSERVACOES VARCHAR(255),
    CONSTRAINT PRIMARY KEY (ID_CURSO)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS TURMA(
    ID_TURMA INTEGER NOT NULL AUTO_INCREMENT, 
    ID_CURSO INTEGER NOT NULL, 
    NOME_TURMA VARCHAR(100), 
    ABREVIACAO_TURMA VARCHAR(15), 
    CICLO VARCHAR(45) NOT NULL,
    PERIODO VARCHAR(45),
    OBSERVACOES VARCHAR(255),
    CONSTRAINT PRIMARY KEY(ID_TURMA),
    CONSTRAINT FK_ID_CURSO_3 FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS ANO_SEMESTRE_TURMA(
    ID_ANO_SEMESTRE INTEGER NOT NULL, 
    ID_TURMA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255) NOT NULL,
    CONSTRAINT FK_ID_ANO_SEMESTRE_1 FOREIGN KEY (ID_ANO_SEMESTRE) REFERENCES ANO_SEMESTRE(ID_ANO_SEMESTRE),
    CONSTRAINT FK_ID_TURMA_2 FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
) ENGINE = innoDB;



CREATE TABLE IF NOT EXISTS ALUNO_TURMA(
    ID_TURMA INTEGER NOT NULL,         
    CODIGO_CARTAO_RFID INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_ID_TURMA_4 FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA), 
    CONSTRAINT FK_ID_CODIGO_CARTAO_RFID_5 FOREIGN KEY (CODIGO_CARTAO_RFID) REFERENCES ALUNO(CODIGO_CARTAO_RFID)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS SALA(
    ID_SALA INTEGER NOT NULL AUTO_INCREMENT, 
    TIPO_DE_SALA VARCHAR(45), 
    NUMERO_SALA INTEGER NOT NULL, 
    DISPONIBILIDADE_SALA BOOLEAN, 
    ANDAR_SALA INTEGER NOT NULL,
    CONSTRAINT PRIMARY KEY(ID_SALA))
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS PROFESSOR(
    /*--ID_PROFESSOR INTEGER NOT NULL AUTO_INCREMENT, */
    CARTAO_RFID_PROFESSOR INTEGER NOT NULL,
    NOME_PROFESSOR VARCHAR(45) NOT NULL, 
    CODIGO_MATRICULA_PROFESSOR INTEGER NOT NULL,
    IDADE_PROFESSOR INTEGER NOT NULL, 
    DATA_NASCIMENTO_PROFESSOR VARCHAR(12) NOT NULL, 
    FORMACAO_PROFISSIONAL_PROFESSOR VARCHAR(45), 
    ESPECIALIZACAO_PROFISSIONAL_PROFESSOR VARCHAR(45), 
    CPF_PROFESSOR VARCHAR(45), 
    RG_PROFESSOR VARCHAR(45), 
    SEXO_PROFESSOR VARCHAR(45), 
    CELULAR_PROFESSOR VARCHAR(45),
    CONSTRAINT PRIMARY KEY (CARTAO_RFID_PROFESSOR)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS DISCIPLINA(
    ID_DISCIPLINA INTEGER NOT NULL AUTO_INCREMENT, 
    NOME_DISCIPLINA VARCHAR(45),
    CARGA_HOARARIA_DISCIPLINA VARCHAR(45),
    ABREVIACAO_DISCIPLINA VARCHAR(45),
    OBSERVACOES VARCHAR(255),
    CONSTRAINT PRIMARY KEY(ID_DISCIPLINA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS DISCIPLINA_CURSO(
    ID_CURSO INTEGER NOT NULL,         
    ID_DISCIPLINA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_ID_CURSO_6 FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO), 
    CONSTRAINT FK_ID_DISCIPLINA_7 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS DISCIPLINA_PROFESSOR(
    ID_DISCIPLINA INTEGER NOT NULL, 
    CARTAO_RFID_PROFESSOR INTEGER NOT NULL, 
    NOME_DISCIPLINA VARCHAR(45), 
    NOME_PROFESSOR VARCHAR(45),
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_CARTAO_RFID_PROFESSOR_8 FOREIGN KEY (CARTAO_RFID_PROFESSOR) REFERENCES PROFESSOR(CARTAO_RFID_PROFESSOR), 
    CONSTRAINT FK_ID_DISCIPLINA_9 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS HORARIO_BASE(
    ID_HORARIO_BASE INTEGER NOT NULL AUTO_INCREMENT, 
    HORA TIME NOT NULL, 
    DESCRICAO VARCHAR(45),
    CONSTRAINT PRIMARY KEY(ID_HORARIO_BASE)
) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS GRADE_PROFESSOR(
    ID_HORARIO_BASE INTEGER NOT NULL, 
    ID_DISCIPLINA INTEGER NOT NULL, 
    ID_TURMA INTEGER NOT NULL,      
    ID_SALA INTEGER NOT NULL, 
    CARTAO_RFID_PROFESSOR INTEGER NOT NULL,
    DIA_SEMANA VARCHAR(45),
    DATA_AULA DATE,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_ID_HORARIO_BASE_10 FOREIGN KEY (ID_HORARIO_BASE) REFERENCES HORARIO_BASE(ID_HORARIO_BASE),
    CONSTRAINT FK_ID_DISCIPLINA_11 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA), 
    CONSTRAINT FK_ID_TURMA_12 FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA), 
    CONSTRAINT FK_ID_SALA_13 FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA), 
    CONSTRAINT FK_CARTAO_RFID_PROFESSOR_14 FOREIGN KEY (CARTAO_RFID_PROFESSOR) REFERENCES PROFESSOR(CARTAO_RFID_PROFESSOR)) 
ENGINE = innoDB;

--SHOW TABLES;
INSERT INTO ALUNO(
    CODIGO_CARTAO_RFID,
    NOME_ALUNO, 
    NOME_MAE_ALUNO, 
    NOME_PAI_ALUNO,
    CODIGO_MATRICULA_ALUNO,
    CPF_ALUNO, 
    SEXO_ALUNO, 
    IDADE_ALUNO, 
    DATA_NASCIMENTO_ALUNO, 
    EMAIL_ALUNO, 
    CELULAR_ALUNO, 
    RG_ALUNO)
    VALUES(
    2000,
    "FELIPE VIEIRA MOTA",
    "MARIA JOSE VIEIRA MOTA",
    "CELIO ALEXANDRE MOTA",
    200640078,
    "39323658871",
    "MASCULINO",
    26,
    03-11-1991,
    "felipevieiramota@gmail.com",
    "+5513981325132",
    "477572789");




INSERT INTO ANO_SEMESTRE(ANO_SEMESTRE,OBSERVACOES)
    VALUES("2017/1","PRIMEIRO SEMESTRE DE 2017");

INSERT INTO ANO_SEMESTRE(ANO_SEMESTRE,OBSERVACOES)
    VALUES("2017/2","SEGUNDO SEMESTRE DE 2017");

INSERT INTO ANO_SEMESTRE(ANO_SEMESTRE,OBSERVACOES)
    VALUES("2016/1","PRIMEIRO SEMESTRE DE 2017");

INSERT INTO ANO_SEMESTRE(ANO_SEMESTRE,OBSERVACOES)
    VALUES("2016/2","SEGUNDO SEMESTRE DE 2017");




INSERT INTO CURSO(NOME_CURSO,TIPO_CURSO,DURACAO,QTD_SEMESTRES,CARGA_HORARIA,OBSERVACOES)
    VALUES("BACHARELADO EM SISTEMAS DE INFORMACAO","GRADUACAO","4 ANOS","8 SEMESTRES","3600 HORAS DE CURSO","CURSO DE TECNOLOGIA DA INFORMACAO");

INSERT INTO CURSO(NOME_CURSO,TIPO_CURSO,DURACAO,QTD_SEMESTRES,CARGA_HORARIA,OBSERVACOES)
    VALUES("BACHARELADO EM ADMINISTRACAO","GRADUACAO","4 ANOS","8 SEMESTRES","3600 HORAS DE CURSO","CURSO DE ADMINISTRACAO");




INSERT INTO TURMA(ID_CURSO,NOME_TURMA,ABREVIACAO_TURMA,CICLO,PERIODO,OBSERVACOES)
    VALUES(1,"2017/1-BACHARELADO EM SISTEMAS DE INFORMACAO-7A","BSI-7A","7","NOTURNO","TURMA DO 7 SEMESTRE DO CURSO DE BACHARELADO EM SISTEMAS DE INFORMACAO");

INSERT INTO ANO_SEMESTRE_TURMA(ID_ANO_SEMESTRE,ID_TURMA,OBSERVACOES)
    VALUES(1,1,"BACHARELADO EM SISTEMAS DE INFORMACOES PRIMEIRO SEMESTRE DE 2017");

INSERT INTO TURMA(ID_CURSO,NOME_TURMA,ABREVIACAO_TURMA,CICLO,PERIODO,OBSERVACOES)
    VALUES(1,"2017/2-BACHARELADO EM SISTEMAS DE INFORMACAO-8A","BSI-8A","8","NOTURNO","TURMA DO 8 SEMESTRE DO CURSO DE BACHARELADO EM SISTEMAS DE INFORMACAO");

INSERT INTO ANO_SEMESTRE_TURMA(ID_ANO_SEMESTRE,ID_TURMA,OBSERVACOES)
    VALUES(2,2,"BACHARELADO EM SISTEMAS DE INFORMACOES PRIMEIRO SEMESTRE DE 2017");

INSERT INTO TURMA(ID_CURSO,NOME_TURMA,ABREVIACAO_TURMA,CICLO,PERIODO,OBSERVACOES)
    VALUES(2,"2017/1-BACHARELADO EM ADMINISTRACAO-1A","ADM-1A","1","NOTURNO","TURMA DO 1 SEMESTRE DO CURSO DE BACHARELADO EM SISTEMAS DE INFORMACAO");

INSERT INTO ANO_SEMESTRE_TURMA(ID_ANO_SEMESTRE,ID_TURMA,OBSERVACOES)
    VALUES(1,3,"BACHARELADO EM ADMINISTRACAO PRIMEIRO SEMESTRE DE 2017");

INSERT INTO TURMA(ID_CURSO,NOME_TURMA,ABREVIACAO_TURMA,CICLO,PERIODO,OBSERVACOES)
    VALUES(2,"2017/1-BACHARELADO EM ADMINISTRACAO-3A","ADM-3A","3","NOTURNO","TURMA DO 3 SEMESTRE DO CURSO DE BACHARELADO EM SISTEMAS DE INFORMACAO");

INSERT INTO ANO_SEMESTRE_TURMA(ID_ANO_SEMESTRE,ID_TURMA,OBSERVACOES)
    VALUES(1,4,"BACHARELADO EM ADMINISTRACAO PRIMEIRO SEMESTRE DE 2017");




INSERT INTO ALUNO_TURMA(ID_TURMA,CODIGO_CARTAO_RFID,OBSERVACOES)
    VALUES(1,2000,"ALUNO INSERIDO NA TURMA BSI-8");

INSERT INTO SALA(TIPO_DE_SALA,NUMERO_SALA,DISPONIBILIDADE_SALA,ANDAR_SALA)
    VALUES("LABORATORIO",14,TRUE,1);

INSERT INTO PROFESSOR(
    CARTAO_RFID_PROFESSOR,
    NOME_PROFESSOR,
    CODIGO_MATRICULA_PROFESSOR,
    IDADE_PROFESSOR, 
    DATA_NASCIMENTO_PROFESSOR, 
    FORMACAO_PROFISSIONAL_PROFESSOR, 
    ESPECIALIZACAO_PROFISSIONAL_PROFESSOR, 
    CPF_PROFESSOR, 
    RG_PROFESSOR, 
    SEXO_PROFESSOR, 
    CELULAR_PROFESSOR)
    VALUES(
    123456,
    "LEANDRO SANCHEZ",
    3000,
    40,
    "09-15-1967",
    "CIENCIAS DA COMPUTACAO",
    "BANCO DE DADOS",
    "32132132132132",
    "897897897987",
    "MASCULINO",
    "+5513879879797");

INSERT INTO DISCIPLINA(NOME_DISCIPLINA,CARGA_HOARARIA_DISCIPLINA,ABREVIACAO_DISCIPLINA,OBSERVACOES)
    VALUES("EMPREENDEDORISMO","40 HORAS","EMPRE.","DISCIPLINA APLICADA PARA A ANALISE DE UMA EMPRESA DO ");

INSERT INTO DISCIPLINA_CURSO(ID_CURSO,ID_DISCIPLINA,OBSERVACOES)
    VALUES(1,1,"DISCIPLINA PARA LINGUAGENS WEB");

INSERT INTO DISCIPLINA_CURSO(ID_CURSO,ID_DISCIPLINA,OBSERVACOES)
    VALUES(2,1,"DISCIPLINA PARA LINGUAGENS WEB");

INSERT INTO DISCIPLINA_PROFESSOR(    
    ID_DISCIPLINA, 
    CARTAO_RFID_PROFESSOR, 
    NOME_DISCIPLINA, 
    NOME_PROFESSOR,
    OBSERVACOES)
    VALUES(
    1,
    123456,
    "LINGUAGEM WEB",
    "LEANDRO SANCHEZ",
    "DISCIPLINA MINISTRADA POR LEANDRO SANCHEZ PARA A TURMA BSI-8");

INSERT INTO HORARIO_BASE(HORA,DESCRICAO)
    VALUES("19:00:00","PRIMEIRO HORARIO DO PERIODO NOTURNO");

INSERT INTO HORARIO_BASE(HORA,DESCRICAO)
    VALUES("19:50:00","SEGUNDO HORARIO DO PERIODO NOTURNO");

INSERT INTO HORARIO_BASE(HORA,DESCRICAO)
    VALUES("20:55:00","TERCEIRO HORARIO DO PERIODO NOTURNO");

INSERT INTO HORARIO_BASE(HORA,DESCRICAO)
    VALUES("21:45:00","QUARTO HORARIO DO PERIODO NOTURNO");

INSERT INTO HORARIO_BASE(HORA,DESCRICAO)
    VALUES("22:35:00","QUINTO HORARIO DO PERIODO NOTURNO");

INSERT INTO GRADE_PROFESSOR(
    ID_HORARIO_BASE, 
    ID_DISCIPLINA, 
    ID_TURMA,      
    ID_SALA, 
    CARTAO_RFID_PROFESSOR,
    DIA_SEMANA, 
    DATA_AULA,
    OBSERVACOES)
    VALUES(
    1,
    1,
    1,
    1,
    123456,
    "1-SEGUNDA-FEIRA",
    "2017-02-20",
    "AULA DE WEB COM O PROFESSOR LEANDRO NO LABO 14 PARA A TURMA BSI-7");

INSERT INTO GRADE_PROFESSOR(
    ID_HORARIO_BASE, 
    ID_DISCIPLINA, 
    ID_TURMA,      
    ID_SALA, 
    CARTAO_RFID_PROFESSOR,
    DIA_SEMANA, 
    DATA_AULA,
    OBSERVACOES)
    VALUES(
    1,
    1,
    1,
    1,
    123456,
    "2-TERCA-FEIRA",
    "2017-02-21",
    "AULA DE WEB COM O PROFESSOR LEANDRO NO LABO 14 PARA A TURMA BSI-7");

INSERT INTO GRADE_PROFESSOR(
    ID_HORARIO_BASE, 
    ID_DISCIPLINA, 
    ID_TURMA,      
    ID_SALA, 
    CARTAO_RFID_PROFESSOR,
    DIA_SEMANA, 
    DATA_AULA,
    OBSERVACOES)
    VALUES(
    1,
    1,
    1,
    1,
    123456,
    "3-QUARTA-FEIRA",
    "2017-02-22",
    "AULA DE WEB COM O PROFESSOR LEANDRO NO LABO 14 PARA A TURMA BSI-7");

INSERT INTO GRADE_PROFESSOR(
    ID_HORARIO_BASE, 
    ID_DISCIPLINA, 
    ID_TURMA,      
    ID_SALA, 
    CARTAO_RFID_PROFESSOR,
    DIA_SEMANA, 
    DATA_AULA,
    OBSERVACOES)
    VALUES(
    1,
    1,
    1,
    1,
    123456,
    "4-QUINTA-FEIRA",
    "2017-02-23",
    "AULA DE WEB COM O PROFESSOR LEANDRO NO LABO 14 PARA A TURMA BSI-7");

INSERT INTO GRADE_PROFESSOR(
    ID_HORARIO_BASE, 
    ID_DISCIPLINA, 
    ID_TURMA,      
    ID_SALA, 
    CARTAO_RFID_PROFESSOR,
    DIA_SEMANA, 
    DATA_AULA,
    OBSERVACOES)
    VALUES(
    1,
    1,
    1,
    1,
    123456,
    "5-SEXTA-FEIRA",
    "2017-02-24",
    "AULA DE WEB COM O PROFESSOR LEANDRO NO LABO 14 PARA A TURMA BSI-7");

SELECT * FROM TURMA T, ANO_SEMESTRE ANS ,ANO_SEMESTRE_TURMA ANST, CURSO C
    WHERE 
        T.ID_TURMA = ANST.ID_TURMA
    AND 
        ANS.ID_ANO_SEMESTRE = ANST.ID_ANO_SEMESTRE
    AND 
        C.ID_CURSO = T.ID_CURSO;

SELECT * FROM TURMA T, CURSO C
    WHERE C.ID_CURSO = T.ID_CURSO
        AND T.NOME_TURMA = '2017/1-BACHARELADO EM ADMINISTRACAO-3A';

SELECT * FROM TURMA;

SELECT 
     T.ABREVIACAO_TURMA
    ,T.NOME_TURMA   
    ,D.CARGA_HOARARIA_DISCIPLINA 
    ,D.NOME_DISCIPLINA
    ,C.NOME_CURSO     
FROM 
     CURSO C
    ,DISCIPLINA D
    ,DISCIPLINA_CURSO DC
    ,TURMA T
WHERE 
    C.ID_CURSO = DC.ID_CURSO
AND D.ID_DISCIPLINA = DC.ID_DISCIPLINA
AND T.ID_CURSO = C.ID_CURSO;

/*
    WHERE NOME_TURMA = '2017/1-BACHARELADO EM ADMINISTRACAO-3A';
/*

SELECT * FROM TURMA T, ANO_SEMESTRE ANS ,ANO_SEMESTRE_TURMA ANST, CURSO C
    WHERE 
        T.ID_TURMA = ANST.ID_TURMA
    AND 
        ANS.ID_ANO_SEMESTRE = ANST.ID_ANO_SEMESTRE
    AND 
        C.ID_CURSO = T.ID_CURSO
    AND 
        T.NOME_TURMA = "BACHARELADO EM SISTEMAS DE INFORMACAO-8";


/*
SELECT * FROM ALUNO_TURMA ALT, ALUNO A, TURMA T
    WHERE A.CODIGO_CARTAO_RFID = ALT.CODIGO_CARTAO_RFID
        AND T.ID_TURMA = ALT.ID_TURMA;

SELECT 
    HB.HORA,
    GP.DIA_SEMANA, 
    P.NOME_PROFESSOR, 
    S.NUMERO_SALA, 
    S.ANDAR_SALA,
    D.NOME_DISCIPLINA,
    T.NOME_TURMA
FROM 
    GRADE_PROFESSOR GP,
    HORARIO_BASE HB,
    DISCIPLINA D,
    TURMA T,
    SALA S,
    PROFESSOR P
WHERE 
    HB.ID_HORARIO_BASE = GP.ID_HORARIO_BASE
AND D.ID_DISCIPLINA = GP.ID_DISCIPLINA
AND T.ID_TURMA = GP.ID_TURMA
AND S.ID_SALA = GP.ID_SALA
AND P.CARTAO_RFID_PROFESSOR = GP.CARTAO_RFID_PROFESSOR
AND GP.DIA_SEMANA = "1-SEGUNDA-FEIRA"
ORDER BY 
    GP.DIA_SEMANA;


SELECT 
    HB.HORA,
    GP.DIA_SEMANA, 
    P.NOME_PROFESSOR, 
    S.NUMERO_SALA, 
    S.ANDAR_SALA,
    D.NOME_DISCIPLINA,
    T.NOME_TURMA
FROM 
    GRADE_PROFESSOR GP,
    HORARIO_BASE HB,
    DISCIPLINA D,
    TURMA T,
    SALA S,
    PROFESSOR P
WHERE 
    HB.ID_HORARIO_BASE = GP.ID_HORARIO_BASE
AND D.ID_DISCIPLINA = GP.ID_DISCIPLINA
AND T.ID_TURMA = GP.ID_TURMA
AND S.ID_SALA = GP.ID_SALA
AND P.CARTAO_RFID_PROFESSOR = GP.CARTAO_RFID_PROFESSOR
AND GP.DIA_SEMANA = "1-SEGUNDA-FEIRA"
ORDER BY 
    GP.DIA_SEMANA;
    


select * from ANO_SEMESTRE;


        
/* PESQUISAR SE ALUNO ESTEVE NA AULA */
/*
SELECT HB.HORA,S.NUMERO_SALA,S.ANDAR_SALA,D.NOME_DISCIPLINA,P.NOME_PROFESSOR,T.NOME_TURMA,A.NOME_ALUNO 
    FROM FREQUENCIA F, SALA S, PROFESSOR P, HORARIO_BASE HB, DISCIPLINA D, TURMA T, ALUNO A
        WHERE F.ID_SALA = S.ID_SALA
            AND F.ID_PROFESSOR = P.ID_PROFESSOR
            AND F.ID_HORARIO_BASE = HB.ID_HORARIO_BASE
            AND F.ID_DISCIPLINA = D.ID_DISCIPLINA
            AND F.ID_TURMA = T.ID_TURMA
            AND F.CODIGO_CARTAO_RFID = A.CODIGO_CARTAO_RFID
            AND A.NOME_ALUNO = "FELIPE VIEIRA MOTA";

/*PESQUSAR ALUNO NA TURMA */


/*

SELECT * FROM ALUNO;

SELECT * FROM ANO_SEMESTRE;

SELECT * FROM CURSO;

SELECT * FROM ANO_SEMESTRE_CURSO;

SELECT * FROM ANO_SEMESTRE ASM, CURSO C, ANO_SEMESTRE_CURSO ASMC
    WHERE ASM.ID_ANO_SEMESTRE = ASMC.ID_ANO_SEMESTRE
    AND C.ID_CURSO = ASMC.ID_CURSO;

SELECT * FROM TURMA;

SELECT * FROM ALUNO_TURMA;

SELECT * FROM ANO_SEMESTRE;

UPDATE ANO_SEMESTRE SET ANO_SEMESTRE = "2017/1" , OBSERVACOES = "PRIMEIRO SEMESTRE DO ANO DE 2017."
    WHERE ID_ANO_SEMESTRE = 1;

SELECT * FROM TURMA T, ANO_SEMESTRE SM, ANO_SEMESTRE_TURMA AN_SM_T
    WHERE T.ID_TURMA = AN_SM_T.ID_TURMA
        AND SM.ID_ANO_SEMESTRE = AN_SM_T.ID_ANO_SEMESTRE;
    */
    