/**
 * Author:  felipe
 * Created: Nov 6, 2017
 */

DROP DATABASE BD_REGRA;
CREATE DATABASE BD_REGRA;
USE BD_REGRA;

/*1 FLUXO - TABELAS PAI*/

CREATE TABLE IF NOT EXISTS DISCIPLINA(
    ID_DISCIPLINA INTEGER NOT NULL AUTO_INCREMENT, 
    NOME_DISCIPLINA VARCHAR(45),    
    ABREVIACAO_DISCIPLINA VARCHAR(45),
    CODIGO_DISCIPLINA VARCHAR(45) NOT NULL,
    CARGA_HOARARIA_DISCIPLINA VARCHAR(45),
    OBSERVACOES VARCHAR(255),
    CONSTRAINT PRIMARY KEY(ID_DISCIPLINA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS CURSO(
    ID_CURSO INTEGER NOT NULL AUTO_INCREMENT, 
    NOME_CURSO VARCHAR(45), 
    TIPO_CURSO VARCHAR(45), 
    DURACAO VARCHAR(45),
    CODIGO_CURSO VARCHAR(45) NOT NULL,
    QTD_SEMESTRES VARCHAR(100),
    CARGA_HORARIA VARCHAR(45),
    OBSERVACOES VARCHAR(255),
    CONSTRAINT PRIMARY KEY (ID_CURSO)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS ALUNO (  
    ID_ALUNO INTEGER NOT NULL AUTO_INCREMENT,
    NOME_ALUNO VARCHAR(255) NOT NULL,
    NOME_MAE_ALUNO VARCHAR(255) NOT NULL,
    NOME_PAI_ALUNO VARCHAR(45) NOT NULL,      
    CPF_ALUNO VARCHAR(45) NOT NULL,
    SEXO_ALUNO VARCHAR(45) NOT NULL,
    IDADE_ALUNO VARCHAR(45) NOT NULL,
    DATA_NASCIMENTO_ALUNO VARCHAR(45) NOT NULL,
    EMAIL_ALUNO VARCHAR(45) NOT NULL,
    CELULAR_ALUNO VARCHAR(45) NOT NULL,
    RG_ALUNO VARCHAR(45) NULL,
    CODIGO_CARTAO_RFID VARCHAR(45) NOT NULL,
    CODIGO_MATRICULA_ALUNO VARCHAR(45) NOT NULL,    
  CONSTRAINT PRIMARY KEY (ID_ALUNO))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ANO_SEMESTRE(
    ID_ANO_SEMESTRE INTEGER NOT NULL AUTO_INCREMENT, 
    ANO_SEMESTRE VARCHAR(45), 
    OBSERVACOES VARCHAR(255),
    CODIGO_ANO_SEMESTRE VARCHAR(45) NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_ANO_SEMESTRE)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS SEMANA_DE_AULA(
    ID_SEMANA_DE_AULA INTEGER NOT NULL AUTO_INCREMENT, 
    NOME_SEMANA_DE_AULA VARCHAR(45), 
    CODIGO_SEMANA_DE_AULA VARCHAR(45) NOT NULL,
    OBSERVACOES VARCHAR(255),    
    CONSTRAINT PRIMARY KEY (ID_SEMANA_DE_AULA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS DIA_DA_SEMANA(
    ID_DIA_DA_SEMANA INTEGER NOT NULL AUTO_INCREMENT, 
    NOME_DIA_DA_SEMANA VARCHAR(45), 
    CODIGO_DIA_DA_SEMANA VARCHAR(45) NOT NULL,
    OBSERVACOES VARCHAR(255),    
    CONSTRAINT PRIMARY KEY (ID_DIA_DA_SEMANA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS HORARIO_BASE(
    ID_HORARIO_BASE INTEGER NOT NULL AUTO_INCREMENT, 
    HORARIO_INICIAL TIME NOT NULL, 
    DESCRICAO VARCHAR(45),
    CODIGO_HORARIO_BASE VARCHAR(45) NOT NULL,
    HORARIO_FINAL TIME NOT NULL,
    CONSTRAINT PRIMARY KEY(ID_HORARIO_BASE)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS PROFESSOR(    
    NOME_PROFESSOR VARCHAR(45) NOT NULL, 
    IDADE_PROFESSOR INTEGER NOT NULL,         
    DATA_NASCIMENTO_PROFESSOR VARCHAR(12) NOT NULL, 
    FORMACAO_PROFISSIONAL_PROFESSOR VARCHAR(45), 
    ESPECIALIZACAO_PROFISSIONAL_PROFESSOR VARCHAR(45), 
    CPF_PROFESSOR VARCHAR(45), 
    RG_PROFESSOR VARCHAR(45), 
    SEXO_PROFESSOR VARCHAR(45), 
    CELULAR_PROFESSOR VARCHAR(45),
    CODIGO_MATRICULA_PROFESSOR VARCHAR(45) NOT NULL,
    CARTAO_RFID_PROFESSOR VARCHAR(45) NOT NULL,
    CONSTRAINT PRIMARY KEY (CARTAO_RFID_PROFESSOR)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS SALA(
    ID_SALA INTEGER NOT NULL AUTO_INCREMENT, 
    TIPO_DE_SALA VARCHAR(45),    
    NUMERO_SALA VARCHAR(45),
    DISPONIBILIDADE_SALA BOOLEAN,
    ANDAR_SALA VARCHAR(11),
    CODIGO_SALA VARCHAR(11),
    OBSERVACOES VARCHAR(255),
    CONSTRAINT PRIMARY KEY(ID_SALA)) 
ENGINE = innoDB;

/*2 FLUXO - TABELAS FILHAS*/

CREATE TABLE IF NOT EXISTS TURMA(
    ID_TURMA INTEGER NOT NULL AUTO_INCREMENT, 
    ID_CURSO INTEGER NOT NULL, 
    NOME_TURMA VARCHAR(100), 
    ABREVIACAO_TURMA VARCHAR(15), 
    CICLO_TURMA VARCHAR(10) NOT NULL,
    CODIGO_TURMA VARCHAR(45) NOT NULL,
    PERIODO VARCHAR(45),
    OBSERVACOES VARCHAR(255),
    CONSTRAINT PRIMARY KEY(ID_TURMA),
    CONSTRAINT FK_ID_CURSO_1 FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS DISCIPLINA_CURSO(
    ID_CURSO INTEGER NOT NULL,         
    ID_DISCIPLINA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_ID_CURSO_2 FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO), 
    CONSTRAINT FK_ID_DISCIPLINA_3 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS ALUNO_TURMA(
    ID_TURMA INTEGER NOT NULL,         
    ID_ALUNO INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_ID_TURMA_4 FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA), 
    CONSTRAINT FK_ID_ALUNO_5 FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS ANO_SEMESTRE_TURMA(
    ID_ANO_SEMESTRE INTEGER NOT NULL, 
    ID_TURMA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255) NOT NULL,
    CONSTRAINT FK_ID_ANO_SEMESTRE_6 FOREIGN KEY (ID_ANO_SEMESTRE) REFERENCES ANO_SEMESTRE(ID_ANO_SEMESTRE),
    CONSTRAINT FK_ID_TURMA_7 FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA))
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS ANO_SEMESTRE_SEMANA_DE_AULA(
    ID_ANO_SEMESTRE INTEGER NOT NULL, 
    ID_SEMANA_DE_AULA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255) NOT NULL,
    CONSTRAINT FK_ID_ANO_SEMESTRE_8 FOREIGN KEY (ID_ANO_SEMESTRE) REFERENCES ANO_SEMESTRE(ID_ANO_SEMESTRE),
    CONSTRAINT FK_ID_SEMANA_DE_AULA_9 FOREIGN KEY (ID_SEMANA_DE_AULA) REFERENCES SEMANA_DE_AULA(ID_SEMANA_DE_AULA))
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS SEMANA_DIA_DE_AULA(
    ID_DIA_DA_SEMANA INTEGER NOT NULL, 
    ID_SEMANA_DE_AULA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255) NOT NULL,
    CONSTRAINT FK_ID_DIA_DA_SEMANA_10 FOREIGN KEY (ID_DIA_DA_SEMANA) REFERENCES DIA_DA_SEMANA(ID_DIA_DA_SEMANA),
    CONSTRAINT FK_ID_SEMANA_DE_AULA_11 FOREIGN KEY (ID_SEMANA_DE_AULA) REFERENCES SEMANA_DE_AULA(ID_SEMANA_DE_AULA))
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS DIA_DA_SEMANA_HORARIO(
    ID_DIA_DA_SEMANA INTEGER NOT NULL, 
    ID_SEMANA_DE_AULA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_ID_DIA_DA_SEMANA_12 FOREIGN KEY (ID_DIA_DA_SEMANA) REFERENCES DIA_DA_SEMANA(ID_DIA_DA_SEMANA),
    CONSTRAINT FK_ID_SEMANA_DE_AULA_13 FOREIGN KEY (ID_SEMANA_DE_AULA) REFERENCES SEMANA_DE_AULA(ID_SEMANA_DE_AULA))
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS DISCIPLINA_HORARIO(
    ID_HORARIO_BASE INTEGER NOT NULL,         
    ID_DISCIPLINA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_ID_HORARIO_BASE_14 FOREIGN KEY (ID_HORARIO_BASE) REFERENCES HORARIO_BASE(ID_HORARIO_BASE), 
    CONSTRAINT FK_ID_DISCIPLINA_15 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS DISCIPLINA_PROFESSOR(
    CARTAO_RFID_PROFESSOR VARCHAR(45) NOT NULL,         
    ID_DISCIPLINA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_CARTAO_RFID_PROFESSOR_16 FOREIGN KEY (CARTAO_RFID_PROFESSOR) REFERENCES PROFESSOR(CARTAO_RFID_PROFESSOR), 
    CONSTRAINT FK_ID_DISCIPLINA_17 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA)) 
ENGINE = innoDB;

CREATE TABLE IF NOT EXISTS HORARIO_SALA(
    ID_HORARIO_BASE INTEGER NOT NULL,         
    ID_SALA INTEGER NOT NULL,
    OBSERVACOES VARCHAR(255),
    CONSTRAINT FK_ID_HORARIO_BASE_18 FOREIGN KEY (ID_HORARIO_BASE) REFERENCES HORARIO_BASE(ID_HORARIO_BASE), 
    CONSTRAINT FK_ID_SALA_19 FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA)) 
ENGINE = innoDB;

/*CADASTROS*/

/*
    -----------------------------------
        CODIGOS DE CADA ENTIDADE 
    -----------------------------------
        #100 -(ID)   = DISCIPLINA
        #200 -(ID)   = CURSO
        #300 -(ID)   = SEMESTRE
        #400 -(RFID) = codigo matricula aluno
        #500 -(ID)   = CODIGO TURMA
        #600 -(ID)   = SEMANA DE AULA
        #700 -(ID)   = DIA_DE_AULA
    -----------------------------------
*/


/*CADASTRANDO UMA DISCIPLINA EM UM CURSO DISPONIVEL*/
INSERT INTO DISCIPLINA(       
    NOME_DISCIPLINA,    
    ABREVIACAO_DISCIPLINA,
    CODIGO_DISCIPLINA,
    CARGA_HOARARIA_DISCIPLINA,
    OBSERVACOES)
    VALUES(
     "PROGRAMACAO ORIENTEDA A OBJETOS"
    ,"POO"
    ,"#100-1"
    ,"40 HORAS"
    ,"DISCIPLINA MINISTRADA PARA INTRODUCAO A PROGRAMACAO ORIENTADA A OBJETOS");

INSERT INTO CURSO(
    NOME_CURSO, 
    TIPO_CURSO, 
    DURACAO,
    CODIGO_CURSO,
    QTD_SEMESTRES,
    CARGA_HORARIA,
    OBSERVACOES)
    VALUES(
     "BACHARELADO EM SISTEMAS DE INFORMACAO"
    ,"GARDUACAO"
    ,"4 ANOS"
    ,"#200-1"
    ,"8"
    ,"3600 HORAS"
    ,"CURSO DE GARDUACAO VOLTADO PARA A AREA DE SISTEMAS");

INSERT INTO DISCIPLINA_CURSO(
    ID_CURSO,         
    ID_DISCIPLINA,
    OBSERVACOES)
    VALUES(
     1
    ,1
    ,"OK");


/* Cadastrando uma turma a um curso*/
INSERT INTO TURMA (
    ID_CURSO, 
    NOME_TURMA, 
    ABREVIACAO_TURMA, 
    CICLO_TURMA,
    CODIGO_TURMA,
    PERIODO,
    OBSERVACOES)
VALUES(
     1
    ,"BACHARELADO EM SISTEMAS DE INFORMACOES-8"
    ,"BSI-8"
    ,"8 CLICLO"
    ,"#500-1"
    ,"NOTURNO"
    ,"TURMA DO SEGUNDO SEMESTRE DE 2017");

 /*CRIANDO UM SEMESTRE E VINCULANDO COM A TURMA*/

INSERT INTO ANO_SEMESTRE(ANO_SEMESTRE,OBSERVACOES,CODIGO_ANO_SEMESTRE)
    VALUES("2017/2","SEGUNDO SEMESTRE DE 2017","#300-1");
   
INSERT INTO ANO_SEMESTRE_TURMA(ID_ANO_SEMESTRE,ID_TURMA,OBSERVACOES)
    VALUES(1,1,"TURMA DE BSI -8 NO SEGUNDO SEMESTRE DE 2017");

/*VINCULANDO UM SEMESTRE A UMA SEMANA DE AULA*/

INSERT INTO SEMANA_DE_AULA(NOME_SEMANA_DE_AULA,CODIGO_SEMANA_DE_AULA,OBSERVACOES)
    VALUES("SEMANA-1-2017","#600-1","PRIMEIRA SEMANA DE 2017/2");

INSERT INTO ANO_SEMESTRE_SEMANA_DE_AULA(ID_ANO_SEMESTRE,ID_SEMANA_DE_AULA,OBSERVACOES)
    VALUES(1,1,"SEMANA 1 DE 2017/2");

/*VINCULANDO UM DIA DA SEMANA A UMA SEMANA DE AULA*/
INSERT INTO DIA_DA_SEMANA(NOME_DIA_DA_SEMANA,CODIGO_DIA_DA_SEMANA,OBSERVACOES)
    VALUES("SEGUNDA-FEIRA","#700-1","PRIMEIRO DIA DA SEMANA");

INSERT INTO SEMANA_DIA_DE_AULA(ID_DIA_DA_SEMANA,ID_SEMANA_DE_AULA,OBSERVACOES)
    VALUES(1,1,"SEGUNDA FEIRA DA SEMANA 1");

/* HORARIO BASE DE AULA*/
INSERT INTO HORARIO_BASE (HORARIO_INICIAL,DESCRICAO,CODIGO_HORARIO_BASE,HORARIO_FINAL)
    VALUES("19:00","","","");

/* Cadastrando um aluno a uma turma */

INSERT INTO ALUNO(
    NOME_ALUNO ,
    NOME_MAE_ALUNO ,
    NOME_PAI_ALUNO ,      
    CPF_ALUNO ,
    SEXO_ALUNO ,
    IDADE_ALUNO ,
    DATA_NASCIMENTO_ALUNO ,
    EMAIL_ALUNO ,
    CELULAR_ALUNO ,
    RG_ALUNO ,
    CODIGO_CARTAO_RFID ,
    CODIGO_MATRICULA_ALUNO)
VALUES(
     "FELIPE VIEIRA MOTA"
    ,"MARIA JOSE VIEIRA"
    ,"CELIO ALEXANDRE MOTA"
    ,"39323658871"
    ,"MASCULINO"
    ,"26"
    ,"11/03/1991"
    ,"felipevieiramota@gmail.com"
    ,"+5513981325132"
    ,"477572789"
    ,"250118440"
    ,"#400-250118440"
);

INSERT INTO ALUNO_TURMA(ID_TURMA,ID_ALUNO,OBSERVACOES)
    VALUES(1,1,"TURMA DE BSI DO SEGUNDO SEMESTRE DE  2017");


/*
SELECT * FROM DISCIPLINA;
SELECT * FROM CURSO;
SELECT * FROM DISCIPLINA_CURSO;
SELECT * FROM ALUNO WHERE CODIGO_CARTAO_RFID = "250118440";


/**************************************************************/

/*CADASTRANDO UMA TRUMA EM UM CURSO DISPONIVEL EPOSTERIORMENTE A UM SEMESTRE*/

/***************************************************************************/